name: Deploy

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mrvn-discord-bot"
          heroku_email: "strickler.16@gmail.com"
          usedocker: true
          docker_heroku_process_type: worker
          docker_build_args: |
            MRVN_TOKEN
            APEX_API_KEY
            TEST_SERVER
        env:
          MRVN_TOKEN: ${{secrets.MRVN_TOKEN}}
          APEX_API_KEY: ${{secrets.APEX_API_KEY}}
          TEST_SERVER: ${{secrets.TEST_SERVER}}
